_target_: src.models.STUNet.backbonetrainer.Trainer

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.1

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10

model:
  _target_: src.models.STUNet.core.STUNet.STUNet
  prefix_token_num: 0

  backbone:

    tokenizer:
      use_adj: true

      patch:
        patch_len: 12
        stride: 12

      temporal:
        d_model: 128
        patch_len: 12
        stride: 12
        save_path: "path-to-ckpt"

      graph_generator:
        d_model: 128
        output_dim: 128
        num_layers: 2
        num_heads: 2
        dropout: 0.1

      graph_encoder:
        d_model: 128
        pool_fun: 'mean'
        patch_dim: 8
        save_path: "path-to-ckpt"

    num_layers: 2
    num_heads: 4
    d_model: 128
  
  forcast:
    d_model: 128
    seq_len: 12
    node_patch_len: 12
    stride: 12
    pred_len: 12

# use_pretrained_weight: False

# compile model for faster training with pytorch 2.0
compile: false
