# @package _global_

defaults:
  - _self_
  - data: largest # choose datamodule with `test_dataloader()` for evaluation
  - model: STUNet
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

# model:
#   use_pretrained_weight: false

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null